docker:
  container_name: qwikcap-vpn
  image_name: qwikcap-wg
exceptions:
- .push.apple.com
- identity.apple.com
- setup.icloud.com
- idmsa.apple.com
- gateway.icloud.com
- metrics.icloud.com
- p45-fmip.icloud.com
- p45-quota.icloud.com
- mask.icloud.com
- mask-h2.icloud.com
- mask-api.icloud.com
- gsp-ssl.ls.apple.com
- gspe1-ssl.ls.apple.com
- gspe3-ssl.ls.apple.com
- gspe7-ssl.ls.apple.com
- gspe11-ssl.ls.apple.com
- gspe15-ssl.ls.apple.com
- gspe21-ssl.ls.apple.com
- gspe35-ssl.ls.apple.com
- gsp64-ssl.ls.apple.com
- captive.apple.com
- ocsp.apple.com
- ocsp2.apple.com
- valid.apple.com
- csp.apple.com
- query.ess.apple.com
- init.ess.apple.com
- id.apple.com
- data.appattest.apple.com
- api.devicecheck.apple.com
- ppq.apple.com
- bag.itunes.apple.com
- xp.apple.com
- mesu.apple.com
- gdmf.apple.com
- xprotect.apple.com
- guzzoni.apple.com
- .siri.apple.com
- ca.csp.apple.com
- pancake.apple.com
- mtalk.google.com
- alt1-mtalk.google.com
- alt2-mtalk.google.com
- alt3-mtalk.google.com
- alt4-mtalk.google.com
- alt5-mtalk.google.com
- alt6-mtalk.google.com
- alt7-mtalk.google.com
- alt8-mtalk.google.com
- fcm.googleapis.com
- fcm-xmpp.googleapis.com
- android.clients.google.com
- play.google.com
- android.googleapis.com
- android.apis.google.com
- accounts.google.com
- play-fe.googleapis.com
- playgateway-pa.googleapis.com
- pay-users-pa.googleapis.com
- androidactivationvalidation-pa.googleapis.com
- spot-pa.googleapis.com
- infinitedata-pa.googleapis.com
- ota.googlezip.net
- connectivitycheck.gstatic.com
- connectivitycheck.android.com
- clients1.google.com
- clients3.google.com
- proxy-safebrowsing.googleapis.com
- attest.android.com
- www.googleapis.com
- ct.googleapis.com
- dns.google
- p45-caldav.icloud.com
- weather-data.apple.com
- updates.cdn-apple.com
- edge-mqtt.facebook.com
- edge-mqtt-fallback.facebook.com
- graph.fb-pigeon.com
- graph.facebook.com
- tags.tiqcdn.com
- google-ohttp-relay-safebrowsing.fastly-edge.com
- www.google.com
proxy:
  control_port: 9292
  host: 127.0.0.1
  port: 8080
vpn:
  interface: WiFi
  listen_port: 51820
  server_ip: 10.13.37.1
  subnet: 10.13.37.0/24
